# Generated by Django 3.1.5 on 2021-01-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestResult',
            new_name='Chart',
        ),
    ]
