# Generated by Django 3.1.5 on 2021-01-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20210128_2251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart',
            new_name='TestResult',
        ),
    ]
