# Generated by Django 3.1.5 on 2021-01-31 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_testresult_test_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='test_result',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test_date',
        ),
        migrations.AddField(
            model_name='testresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testresult',
            name='username',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
